# Generated by Django 5.1.5 on 2025-07-12 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_id', models.CharField(max_length=50)),
                ('interval_minutes', models.PositiveSmallIntegerField()),
                ('total_rounds', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microworkouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicroRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('microworkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='microworkouts.microworkout')),
            ],
        ),
    ]
